### ISSUE TITLE
gyp WARN EACCES user "nobody" does not have permission to access during build

### ISSUE THREAD

**Issue by bigperson** [lagun4ik/docker-images#1]
I want to build container with laravel-echo-server

DockerFile:
```dockerfile
FROM node:alpine

RUN apk add --update --no-cache bash \
	&& apk add --update --no-cache -t .build-deps python make g++ gcc \
	&& npm i -g laravel-echo-server \
	&& apk del .build-deps

WORKDIR /app

ENTRYPOINT ["laravel-echo-server"]
CMD ["start"]

EXPOSE 8888
```

docker-compose.yml
```yml
....
    node:
          build:
             context: ./docker/node
          expose:
              - "8888"
          ports:
              - "8888:8888"
          volumes:
              - ./:/app
          links:
              - redis
          command: 'npm start'
...
```

I have warnings and сan not build container:
```
gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/.node-gyp/8.4.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/.node-gyp"
```
